# Path: render.yaml (در ریشه پروژه - کنار پوشه‌های beauty-backend و beauty-frontend)
services:
  - type: web
    name: eshaghi2
    runtime: node
    repo: https://github.com/eshaghi272/Eshaghi2
    plan: free
    rootDir: beauty-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health